# Generated by Django 2.2.4 on 2019-08-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190824_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'permissions': [('blogger', 'create update and delete blogs')]},
        ),
    ]
